#!/usr/bin/env python

import os

from argcmdr import Command, main


class Main(Command):
    """print the current directory's contents"""

    def __init__(self, parser):
        parser.add_argument(
            '-1',
            action='store_const',
            const='\n',
            default=' ',
            dest='sep',
            help='list one file per line',
        )

    def __call__(self, args):
        print(*os.listdir(), sep=args.sep)


if __name__ == '__main__':
    main(Main)
